# example values
server:
  port: 8080

spring.datasource.url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username: root
spring.datasource.password: 1234
spring.jpa.hibernate.ddl-auto: create
started:
  sites:
    - url: https://nikoartgallery.com
      name: Галерея Нико
    - url: http://radiomv.ru
      name: Радио Милицейская Волна
    - url: https://www.lutherancathedral.ru
      name: Кафедральный собор святых Петра и Павла
    - url: https://ipfran.ru
      name: ИПФ РАН
    - url: http://www.playback.ru/
      name: Интернет-магазин playback.ru
    - url: https://dimonvideo.ru/
      name: DimonVideo - программы | игры | фильмы | книги

  field:
    - name: title
      selector: title
      weight: 1.0
    - name: body
      selector: body
      weight: 0.8

# максимальный процент появления Lema от общего количества страниц в поиске
lemma-frequency:
  percent: 60

user-agent:
  name: FastSearchBot/1.0
